In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input/kddcup.data"))

# Any results you write to the current directory are saved as output.

['kddcup.data']

In [2]:
import pandas as pd
df = pd.read_csv('../input/kddcup.data/kddcup.data')

In [3]:
df.shape

(4898430, 42)

In [4]:
df.columns =["duration","protocol_type","service","flag","src_bytes",
    "dst_bytes","land","wrong_fragment","urgent","hot","num_failed_logins",
    "logged_in","num_compromised","root_shell","su_attempted","num_root",
    "num_file_creations","num_shells","num_access_files","num_outbound_cmds",
    "is_host_login","is_guest_login","count","srv_count","serror_rate",
    "srv_serror_rate","rerror_rate","srv_rerror_rate","same_srv_rate",
    "diff_srv_rate","srv_diff_host_rate","dst_host_count","dst_host_srv_count",
    "dst_host_same_srv_rate","dst_host_diff_srv_rate","dst_host_same_src_port_rate",
    "dst_host_srv_diff_host_rate","dst_host_serror_rate","dst_host_srv_serror_rate",
    "dst_host_rerror_rate","dst_host_srv_rerror_rate","label"]

In [5]:
df.shape

(4898430, 42)

In [6]:
df.head()

   duration protocol_type   ...    dst_host_srv_rerror_rate    label
0         0           tcp   ...                         0.0  normal.
1         0           tcp   ...                         0.0  normal.
2         0           tcp   ...                         0.0  normal.
3         0           tcp   ...                         0.0  normal.
4         0           tcp   ...                         0.0  normal.

[5 rows x 42 columns]

In [7]:
newlabeldf=df['label'].replace({ 'normal.' : 0, 'neptune.' : 1 ,'back.': 1, 'land.': 1, 'pod.': 1, 'smurf.': 1, 'teardrop.': 1,'mailbomb.': 1, 'apache2.': 1, 'processtable.': 1, 'udpstorm.': 1, 'worm.': 1,
                           'ipsweep.' : 2,'nmap.' : 2,'portsweep.' : 2,'satan.' : 2,'mscan.' : 2,'saint.' : 2
                           ,'ftp_write.': 3,'guess_passwd.': 3,'imap.': 3,'multihop.': 3,'phf.': 3,'spy.': 3,'warezclient.': 3,'warezmaster.': 3,'sendmail.': 3,'named.': 3,'snmpgetattack.': 3,'snmpguess.': 3,'xlock.': 3,'xsnoop.': 3,'httptunnel.': 3,
                           'buffer_overflow.': 4,'loadmodule.': 4,'perl.': 4,'rootkit.': 4,'ps.': 4,'sqlattack.': 4,'xterm.': 4})
df['label'] = newlabeldf
#df['target'] = newlabeldf
print(df['label'].head())

0    0
1    0
2    0
3    0
4    0
Name: label, dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898430 entries, 0 to 4898429
Data columns (total 42 columns):
duration                       int64
protocol_type                  object
service                        object
flag                           object
src_bytes                      int64
dst_bytes                      int64
land                           int64
wrong_fragment                 int64
urgent                         int64
hot                            int64
num_failed_logins              int64
logged_in                      int64
num_compromised                int64
root_shell                     int64
su_attempted                   int64
num_root                       int64
num_file_creations             int64
num_shells                     int64
num_access_files               int64
num_outbound_cmds              int64
is_host_login                  int64
is_guest_login                 int64
count                          int64
srv_count                      int64
serror_rate                    float64
srv_serror_rate                float64
rerror_rate                    float64
srv_rerror_rate                float64
same_srv_rate                  float64
diff_srv_rate                  float64
srv_diff_host_rate             float64
dst_host_count                 int64
dst_host_srv_count             int64
dst_host_same_srv_rate         float64
dst_host_diff_srv_rate         float64
dst_host_same_src_port_rate    float64
dst_host_srv_diff_host_rate    float64
dst_host_serror_rate           float64
dst_host_srv_serror_rate       float64
dst_host_rerror_rate           float64
dst_host_srv_rerror_rate       float64
label                          int64
dtypes: float64(15), int64(24), object(3)
memory usage: 1.5+ GB

In [9]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
le = LabelEncoder()
df['protocol_type'] = le.fit_transform(df['protocol_type'])
df['service']= le.fit_transform(df['service'])
df['flag'] = le.fit_transform(df['flag'])

In [10]:
X = df.iloc[:,:41]
y = df.iloc[:,-1]

In [11]:
X.head()

   duration            ...             dst_host_srv_rerror_rate
0         0            ...                                  0.0
1         0            ...                                  0.0
2         0            ...                                  0.0
3         0            ...                                  0.0
4         0            ...                                  0.0

[5 rows x 41 columns]

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state = 34,test_size = 0.3)

In [13]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

/opt/conda/lib/python3.6/site-packages/sklearn/preprocessing/data.py:334: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)

In [14]:
from sklearn.ensemble import RandomForestClassifier
model1 = RandomForestClassifier(n_estimators=100, max_depth=2,random_state=0,class_weight='balanced')
model1.fit(X_train_scaled,y_train)

RandomForestClassifier(bootstrap=True, class_weight='balanced',
            criterion='gini', max_depth=2, max_features='auto',
            max_leaf_nodes=None, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=100, n_jobs=None, oob_score=False, random_state=0,
            verbose=0, warm_start=False)

In [15]:
predict = model1.predict(X_test_scaled)

In [16]:
model1.score(X_test_scaled,y_test)

0.9368886221367526

In [17]:
model1.score(X_train_scaled,y_train)

0.9367934507295487

In [18]:
from sklearn.metrics import confusion_matrix,recall_score,precision_score
print((confusion_matrix(y_test,predict)))

[[ 218245    1936   38217   31943     915]
 [   7167 1146110   12087     262       0]
 [    107      55   12108      14       2]
 [      4       0      18     309      10]
 [      0       0       1       6      13]]

In [19]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predict))

              precision    recall  f1-score   support

           0       0.97      0.75      0.84    291256
           1       1.00      0.98      0.99   1165626
           2       0.19      0.99      0.32     12286
           3       0.01      0.91      0.02       341
           4       0.01      0.65      0.03        20

   micro avg       0.94      0.94      0.94   1469529
   macro avg       0.44      0.85      0.44   1469529
weighted avg       0.99      0.94      0.96   1469529